// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaogwkgdkdwitbfwmsmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhb2d3a2dka2R3aXRiZndtc211Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDgyMjgsImV4cCI6MjA3MzE4NDIyOH0.BREkyM6Wl3RAu8iie9CgDy9goJTmaKO7AT_66hQAjQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});